- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/ChannelBindingProperties.java
- Use `TreeMap` for channel bindings and set case insensitive comparator for the tree map.
- This way binding key (typically channel name) can be looked up case insensitively
> Make binding key case insensitive

- spring-cloud-stream-samples/double/pom.xml
- spring-cloud-stream-samples/extended/pom.xml
- spring-cloud-stream-samples/extended/src/main/java/extended/ExtendedApplication.java
- spring-cloud-stream-samples/pom.xml
- spring-cloud-stream-samples/sink/pom.xml
- spring-cloud-stream-samples/sink/src/main/java/demo/LogSink.java
- spring-cloud-stream-samples/sink/src/main/java/demo/SinkApplication.java
- spring-cloud-stream-samples/sink/src/test/java/demo/ModuleApplicationTests.java
- spring-cloud-stream-samples/source/pom.xml
- spring-cloud-stream-samples/source/src/main/java/demo/DateFormat.java
- spring-cloud-stream-samples/source/src/main/java/demo/SourceApplication.java
- spring-cloud-stream-samples/source/src/main/java/demo/TimeSource.java
- spring-cloud-stream-samples/source/src/main/java/demo/TimeSourceOptionsMetadata.java
- spring-cloud-stream-samples/tap/pom.xml
- spring-cloud-stream-samples/tap/src/main/java/demo/TapApplication.java
- spring-cloud-stream-samples/tap/src/main/java/demo/TappingLoggingSink.java
- spring-cloud-stream-samples/transform/pom.xml
- spring-cloud-stream-samples/transform/src/main/java/demo/LoggingTransformer.java
- spring-cloud-stream-samples/transform/src/main/java/demo/TransformApplication.java
- Move common properties to samples parent
- Avoid explicit `ComponentScan` by moving all the classes to the same package
> Samples cleanup

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/Bindable.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindableProxyFactory.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingBeanDefinitionRegistryUtils.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingProperties.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/ChannelBindingAutoConfiguration.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/endpoint/ChannelsEndpoint.java
Bindable picks up 2 new methods to enumerate the binding names, and then
it's a simple matter to list all the inputs and outputs and their
properties.
Fixes gh-149
> Add ChannelsEndpoint back for introspecting bindings

- spring-cloud-stream-binders/spring-cloud-stream-binder-rabbit/src/test/java/org/springframework/cloud/stream/binder/rabbit/RabbitBinderTests.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/ChannelBindingService.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingProperties.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binding/ChannelBindingServiceTests.java
Resolves #211
Add a default UUID to the `BindingProperties.group` so a pubsub binding is
unique unless the group is specifically set.
> GH-211: PubSub Group Default to Random UUID

- spring-cloud-stream-binders/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/config/RabbitServiceAutoConfiguration.java
- spring-cloud-stream-binders/spring-cloud-stream-binder-rabbit/src/test/java/org/springframework/cloud/stream/binder/rabbit/integration/RabbitBinderModuleTests.java
- spring-cloud-stream-binders/spring-cloud-stream-binder-redis/src/test/java/org/springframework/cloud/stream/binder/redis/integration/RedisBinderModuleTests.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/BinderConfiguration.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BinderFactoryConfiguration.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BinderProperties.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/BinderFactoryConfigurationTests.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binding/ChannelBindingServiceTests.java
Resolves #229
Optimizes connection factory creation for binders that can use Boot's autoconfiguration
> Binders with default settings inherit from module's configuration

- spring-cloud-stream-binders/pom.xml
- spring-cloud-stream-dependencies/pom.xml
- spring-cloud-stream-samples/pom.xml
- spring-cloud-stream-starters/pom.xml
- spring-cloud-stream-starters/spring-cloud-starter-stream-rabbit/pom.xml
It actually still has to be managed using a property in
spring-cloud-stream-binders-parent, but this change is for users.
Any user that wants an app using stream and rabbit needs to use the
spring-cloud-dependencies BOM. A gradle user has to do nothing else
with this change. A maven user still has to add an explicit
<spring-aqmp.version/> to the application POM.
> Add spring-rabbit explicitly to the dependencies BOM

- spring-cloud-stream-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
In the context of trying to configure Rabbit, the docs mention that the Rabbit config properties be added under `rabbit`:
```
...
binders:
rabbit1:
type: rabbit
environment:
spring:
rabbit: <-- here
host: <host1>
...
```
however, the properties should be configured under `rabbitmq` as reference in the [Spring Boot Appendix A](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
> Rabbit binder environment should be named rabbitmq

- spring-cloud-stream-binders/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java
- spring-cloud-stream-binders/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitMessageChannelBinder.java
- spring-cloud-stream-binders/spring-cloud-stream-binder-redis/src/main/java/org/springframework/cloud/stream/binder/redis/RedisMessageChannelBinder.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractBinder.java
- subclasses should implement the new onInit() method instead of overriding
- avoids the potential for a NPE in case an overriding subclass did not call the superclass method
> AbstractBinder's afterPropertiesSet() is now final

- spring-cloud-stream-binders/spring-cloud-stream-binder-test/src/test/java/org/springframework/cloud/stream/binder/MessageChannelBinderSupportTests.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractBinder.java
- When deserializing the payload at the consumer endpoint, the non-byte stream payload type requires to use `String` object when the underlying message content-type is of any `text` type contentType (text/plain, text/xml and text/html).
- This fix is only needed to support any non-SCSt applications that will have the 'text/*` contentType of the deserializing message
- Add test
This resolves #403
> Support text/* contentType sent by non-SCSt applications

- spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/ContentTypeConfigurerTests.java
- spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/MessageChannelConfigurerTests.java
- spring-cloud-stream-integration-tests/src/test/resources/org/springframework/cloud/stream/config/channel/source-channel-configurers.properties
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/MessageConverterConfigurer.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/ChannelBindingServiceConfiguration.java
- Add a `MessageChannelConfigurer` that uses a channel interceptor to check if the message contentType header is missing and if there is a binding property for `contentType` header is provided, then set that value as the message contentType header
- This resolves #397
> Set message header using BindingProperties' contentType

- spring-cloud-stream-binders/spring-cloud-stream-binder-kafka/pom.xml
> Exclude log4j as a Kafka binder dependency

- spring-cloud-stream-binders/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderConfigurationProperties.java
can't configure properly otherwise
> add missing accessors for configuration properties' array members

- spring-cloud-stream-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
Docs is missing the 'producer' key. It was a honest mistake to copy and paste on a sample and not get the partitioning configured for the producer.
> Fixing partition section where 'producer' key was missing from example'

- spring-cloud-stream-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
- Remove `ignored by Kafka` for the retry properties
> Fix retry consumer properties for Kafka

- spring-cloud-stream-binders/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java
Fixes #543
We don't need another ThreadFactory implementation and can use Spring Framework class instead.
Backport to 1.0.x.
> Use CustomizableThreadFactory for Kafka Binder

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java
Since this is an internal construct, we can safely ignore
the application settings.
> Set an explicit context class for the binders

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java
- allow the use of the destination reference returned by
`createProducerDestinationIfNecessary` when invoking `createProducerMessageHandler`
> Refactor AbstractMessageChannelBinder

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java
Fixes #741
The current code will skip `deserializePayloadIfNecessary` if the
payload is a `byte[]`. There are in fact two conditions that indicate
that a message does not require postprocessing in the binder: that
the payload is not a `byte[]` which indicates that the message has
already been deserialized, and that the `originalContentType` is not
present, or else it'd need to be moved to `contentType`. This fix
adds the secondary condition to the check.
Note: this requires backporting to the 1.1.x branch.
> Skip `deserializePayloadIfNecessary` only if `originalContentType` is not set

- spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
It is an absolute number of attempts, not the number of retries.
> Fix Incorrect Docs for consumer.maxAttempts

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/EnvironmentEntryInitializingTreeMap.java
> "spring.cloud.stream.default" prefix is not used by BindingServiceProperties

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java
> AbstractMessageChannelBinder can have a `null` headers list

- spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/aggregate/AggregateApplicationTests.java
- spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/aggregate/processor/TestProcessor.java
- spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/aggregate/source/TestSource.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceConfiguration.java
- Remove conditionalOnMissingBean check on the necessary beans that are required for exernal bindings of the child application
- Add test to verify
Resolves #816
> Fix non self-contained aggregate application binding

- spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/StreamListenerAsMetaAnnotationTests.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerAnnotationBeanPostProcessor.java
Contains the changes in #840 and fix for #841
> Properly handle `@StreamListener` as meta-annotations

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerAnnotationBeanPostProcessor.java
> Allow `StreamListenerParameterAdapter` to be applied more broadly

- spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
- spring-cloud-stream-metrics/src/main/java/org/springframework/cloud/stream/metrics/ApplicationMetrics.java
- spring-cloud-stream-metrics/src/main/java/org/springframework/cloud/stream/metrics/ApplicationMetricsExporter.java
- spring-cloud-stream-metrics/src/main/java/org/springframework/cloud/stream/metrics/ApplicationMetricsProperties.java
- spring-cloud-stream-metrics/src/main/java/org/springframework/cloud/stream/metrics/config/BinderMetricsAutoConfiguration.java
- spring-cloud-stream-metrics/src/main/java/org/springframework/cloud/stream/metrics/config/BinderMetricsEnvironmentPostProcessor.java
- spring-cloud-stream-metrics/src/main/java/org/springframework/cloud/stream/metrics/config/Emitter.java
- spring-cloud-stream-metrics/src/test/java/org/springframework/cloud/stream/metrics/ApplicationMetricsExporterTests.java
- spring-cloud-stream-metrics/src/test/java/org/springframework/cloud/stream/metrics/RelaxedPropertiesUtilsTests.java
- Change the metrics channel name to `applicationMetricsChannel`
- Update documentation
- Remove `instanceIndex` to reduce coupling to
Spring Cloud Stream semantics and because it can be sent via
the `properties` metadata set
> Metrics refactoring

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BinderAwareChannelResolver.java
Fixes https://github.com/spring-cloud/spring-cloud-stream/issues/931
While the resolver binds the channel and registers the bean in a synchronized block,
it does not re-check that another thread has already done the work.
Add a second `super.resolveDestination()` to the synchronized block.
> GH-931: Fix BinderAwareChannelResolver Concurrency

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceConfiguration.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/SourceBindingWithBindingTargetsTests.java
Resolves: https://github.com/spring-cloud/spring-cloud-stream/issues/943 #943
There is a current limitation in that the contentType is not currently
stripped if the message is forward unchanged. But this is likely unusual.
See https://jira.spring.io/browse/INT-4272
> GH-943: Don't Propagate contentType

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinderTests.java
- If the endpoints produced by `createConsumer` or
`createProducers` and Spring `DisposableBean` instances
then call `Destroy` on unbind.
Fix #953
> AbstractMessageChanelBinder observes Disposable

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/MessageConverterConfigurer.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binding/MessageConverterConfigurerTests.java
Fixes #993
If the converter cannot convert due to a lingering content-type header, take a second
shot with the header removed.
If we still fail, throw a `MessageConversionException`.
> GH-993: Conversion Interceptor Improvements

- spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
Simple paragraph helping users understand VCAP_SERVICES, points to dataflow server much broader explanation.
Fixes https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/87
> Adding section on cloudfoundry and VCAP_SERVICES

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceProperties.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/EnvironmentEntryInitializingTreeMap.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/SourceBindingWithGlobalPropertiesOnlyTest.java
- When binding the default BindingProperties, we use RelaxedDataBinder without any specific conversion service. This makes the `String` to SpEL `Expression` conversion failing when the producer properties such as `partitionKey/SelectorExpression` are bound.
- Update the underlying conversion service (which includes the SpELConverter via EnableBinding) into RelaxedDataBinder
- Update test
Resolves #1040
> Use conversion service when binding default properties

- spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/AbstractAvroMessageConverter.java
- spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/AvroMessageConverterAutoConfiguration.java
- spring-cloud-stream-schema/src/test/java/org/springframework/cloud/schema/avro/AvroMessageConverterSerializationTests.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/OriginalContentTypeResolver.java
- Fixes #1072 
- Added a new ContentTypeResolver that searches for originalContentType
as well as contentType headers
- This should fix issues with converters not being able to find the proper contentType information. The new Resolver could be used in 2.0 line as a fallback to read messages from 1.3 producers
> Fixes issue with originalContentTypeHeader

- spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/LegacyContentTypeTests.java
- spring-cloud-stream-integration-tests/src/test/resources/org/springframework/cloud/stream/config/channel/legacy-sink-channel-configurers.properties
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/MessageConverterConfigurer.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingProperties.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binding/MessageConverterConfigurerTests.java
Fixes #1057
Enable consumers to convert from originalContentType to contentType in the case of
legacy producers sending messages with originalContentType header.
By default, this conversion will not happen and only be acitvated by setting
`spring.cloud.stream.bindings.input.legacyContentTypeHeaderEnabled` to true.
> Default interceptor for legacy contentType

- spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
Without explicitly naming the `inputChannel` and `outputChannel`, well get this error on startup `org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers`.
Also adding the `// Imports omitted` that appeared in the other Application classes.
> Fixing @Transformer for ProcessorApplication.

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/MessageSerializationUtils.java
See https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/223
When using native encoding; NPE when no class name derived from the content type.
Do not attempt deserialization if `JavaClassMimeTypeUtils.classNameFromMimeType(contentType)`
returns `null`.
Test case in the Kafka binder.
__cherry-pick to master__
> KAFKA GH-223: Handle unexpected content type

- spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
- critiical -> critical;
- end 'etc' with a period; also consistently end etc in parentheses with
'etc.).';
- typo in 'application';
- applicaiton -> application;
> Fix typos in spring-cloud-stream-overview.adoc

- spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/aggregate/AggregateApplicationTests.java
- spring-cloud-stream-test-support/src/test/java/org/springframework/cloud/stream/test/aggregate/main/AggregateWithMainTest.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/aggregation/AggregationTest.java
Ensured AggregateApplicationTests, AggregateWithMainTest and AggregationTest arn't using default 8080 port
> GH-1126 Fixed default app port in Tests

- spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
- fixed directive on how to enable only 'bindings' endpoint
- reworked documentation to reflect the recent fix in #1286
Resolves #1285
> GH-1285 Fixed binding control docs

- spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
The images in the reference guide are not very readable right now. This PR attempts to fix the image width.
- Change width from 300 -> 800 for all the images
- Align all the images in the center
This PR also adds a note re: SCST 2.0 on CF.
> Adjust image-width

- spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/AvroSchemaRegistryClientMessageConverter.java
The NPE was a result of not following defensive programming practices and that is fixed.
Also, we already support both reader and writer schema being null where new ReflectDatumReader(type) is used in getDatumReader(..)  operation.
That said there may still be conditions which are not supported and that is okay since in the end it's a MessageConverter and as such it is one
of the extension points of the framework allowing user to provide a custom one follwing instructions in 'User-defined Message Converters' of the reference guide.
Resolves #1294
> GH-1294 Fixed NPE in AvroSchemaRegistryClientMessageConverter

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/ListenerContainerCustomizer.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binding/BindingServiceTests.java
This work is basically parsing out some rabbit specific work from https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/pull/145 into a an AbstractMessageChannelBinder
Resolves #1399
> GH-1399 Added support for listener container customizer

- spring-cloud-stream/pom.xml
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/annotation/StreamMessageConverter.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/ContentTypeConfiguration.java
After fixing https://jira.spring.io/browse/INT-4517 we don't need
a hack in the `ContentTypeConfiguration` about removal of the
`IntegrationContextUtils.ARGUMENT_RESOLVER_MESSAGE_CONVERTER_BEAN_NAME`
`BeanDefinition` and registering our own later
* Provide some code polishing for the `ContentTypeConfiguration`
removing some redundant code and providing consistency with
components it uses
* Add `ElementType.PARAMETER` target for the `StreamMessageConverter`
annotation to let the list of appropriate converters to be inject
via method parameters in the `@Bean` definition
* Tentative use SI `5.1.0.BUILD-SNAPSHOT` until Spring Boot 2.1 M2
> Revert ContentTypeConfiguration changes

- mvnw
- mvnw.cmd
- pom.xml
- spring-cloud-stream-binder-test/pom.xml
- spring-cloud-stream-core-docs/pom.xml
- spring-cloud-stream-integration-tests/pom.xml
- spring-cloud-stream-reactive/pom.xml
- spring-cloud-stream-schema-server/pom.xml
- spring-cloud-stream-schema/pom.xml
- spring-cloud-stream-test-support-internal/pom.xml
- spring-cloud-stream-test-support/pom.xml
- spring-cloud-stream-tools/pom.xml
- spring-cloud-stream/pom.xml
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://docs.spring.io/spring-framework/docs/ with 1 occurrences migrated to:  
https://docs.spring.io/spring-framework/docs/ ([https](https://docs.spring.io/spring-framework/docs/) result 200).
* http://docs.spring.io/spring-shell/docs/current/api/ with 1 occurrences migrated to:  
https://docs.spring.io/spring-shell/docs/current/api/ ([https](https://docs.spring.io/spring-shell/docs/current/api/) result 200).
* http://maven.apache.org/xsd/maven-4.0.0.xsd with 11 occurrences migrated to: …
> URL Cleanup

- docs/src/main/asciidoc/binders.adoc
- docs/src/main/asciidoc/spring-cloud-stream.adoc
Fixed broken links for Azure Event Hubs Binder.
> Azure Event Hubs binder url fixed on docs

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceConfiguration.java
Starting with version 5.2 Spring Integration provides a global
`DestinationResolver` bean for some runtime optimization using a single
object.
With that the `binderAwareRouterBeanPostProcessor` bean can't resolve
a single `DestinationResolver` bean any more since there is now two
instances of that.
* Fix `BindingServiceConfiguration.binderAwareRouterBeanPostProcessor()`
to use `@Qualifier("binderAwareChannelResolver")` for an explicit bean
resolution for injection.
> Fix BindingServiceConfiguration for SI-5.2

- spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/QualifiedSubjectNamingStrategy.java
Currently `QualifiedSubjectNamingStrategy` generates a subject name that repects the uppercase letters of the schema, producing strings such as `org.company.events.SomeEvent`.
This subject name is used to register the schema in the schema registry. 
The problem is when the consumer is receiving a message, `MessageConverterConfigurer.doPreSend()` changes the contentType, lowerCasing it here:
```
headersMap.put(MessageHeaders.CONTENT_TYPE, MimeType.valueOf(
(String) message.getHeaders().get(MessageHeaders.CONTENT_TYPE)));
```
Then when the consumer asks the schema registry for a schema `application/vnd.org.company.events.someevent.v1+avro` it fails since it doesn't exactly match the capital letters.
With this change the schema will be registered with lower case so this won't fail anymore.
> QualifiedSubjectNamingStrategy uses lowercase

- docs/src/main/asciidoc/spring-cloud-stream.adoc
During reading the documentation I found some small typos and corrected them.
> Typos in Documentation

- docs/src/main/asciidoc/binders.adoc
- docs/src/main/asciidoc/sagan-index.adoc
- docs/src/main/asciidoc/spring-cloud-stream.adoc
The project site is already also updated with the link: https://spring.io/projects/spring-cloud-stream
> Add RocketMQ to the binders list

- README.adoc
The functional binding requires the binding to be "log-in-0" rather than "input"
> Fixing functional binding

- docs/src/main/asciidoc/index.adoc
- docs/src/main/asciidoc/spring-cloud-stream.adoc
Fixed several small typos/ambiguities in SCSt docs. How does one regen (within the context of this repo) the resultant HTML from Asciidoc files to verify, or is it handled by the pipeline? I typically do it manually on sites I manage, just wanted to be sure changes are reflected in output. Thanks! (And more to come!)
> Fixed various small typos/ambiguities in docs

- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/ReactiveFunctionWithNativeEncodingTests.java
When native encoding is enabled with a reactive function,
Spring Cloud Stream is still trying to convert the message
causing ClassCastException and other potential issues downstream.
Fixing this issue by signaling the framework to not perform any
message conversion on the outbound when useNativeEncoding is
enabled with a reactive function.
Resovles https://github.com/spring-cloud/spring-cloud-stream/issues/2037
> Reactive functions and native encoding

- docs/src/main/asciidoc/spring-cloud-stream.adoc
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/BinderCustomizer.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceConfiguration.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/BinderFactoryAutoConfigurationTests.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/ExtendedPropertiesDefaultTests.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/stub1/StubBinder1.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/stub2/StubBinder2.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binding/BindingServiceTests.java
Enable applications with multi binders to provide customizations for
the binders. This is accomplished by providing a new API called
BinderCustomizer. When an implementation is found for this interface,
the customizations are applied against the binders before providing access to them.
Tests and docs.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/1541
> Muti binder customization

- docs/src/main/asciidoc/spring-cloud-stream.adoc
Fixing typo in documentation that caused a broken view.
See https://docs.spring.io/spring-cloud-stream/docs/3.0.12.RELEASE/reference/html/spring-cloud-stream.html#_programmatic_way
> Fixed typo in spring-cloud-stream.adoc

- docs/src/main/asciidoc/spring-cloud-stream.adoc
- spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java
- spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/StreamBridgeTests.java
Currently, when `StreamBridge` creates an output binding, the framework
applies all the available channel interceptors on it by default. This
creates unwanted side effects and the application does not have a way
to control this. Change this behavior by only applying channel interceptors
annoatated with `@GlobalChannelInterceptor`. This way, the user can
provide patterns to decide which interceptors need to be applied on
specific `StreamBridge` bindings.
Adding tests to verify.
Adding docs.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2180
> StreamBridge and ChannelInterceptors enhancements

- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderTests.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/ConsumerProperties.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/ProducerProperties.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java
- core/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binding/BindingServiceTests.java
Make binding names available through Consumer/Producer properties.
Currently, the binders use a ThreadLocal to store the binding name for internal use.
These changes introduce the binding name as a property for both producer/consumer bindings.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2380
> Binding name as a consumer/producer property

- samples/confluent-schema-registry-integration/confluent-schema-registry-integration-consumer/pom.xml
- samples/confluent-schema-registry-integration/confluent-schema-registry-integration-producer1/pom.xml
- samples/confluent-schema-registry-integration/confluent-schema-registry-integration-producer2/pom.xml
- samples/confluent-schema-registry-integration/pom.xml
- samples/pom.xml
@sobychacko I noticed when review the Kafka native sample that the Confluent schema registry sample was a bit inconsistent. I believe the original PR had the `avro-samples` intermediate level pom removed for simplicity and I think this may have been a "miss" from that. 
Anyways, comments inline.
> Make confluent-schema-registry-integration sample poms consistent

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/SerdeResolverUtilsTests.java
@sobychacko since this property is required for a properly functioning application context I wanted to move it up so that all of the AC runners in the test get the required property. Otherwise there are some negative tests whose failure may not be the exact thing it is expecting but instead a failure induced by the missing property. This also allows us to set the property in fewer places.
> Simplify SerdeResolverUtilsTests setting of ineligible-definitions

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderEnvironmentPostProcessor.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderEnvironmentPostProcessorTests.java
* KafkaStreamsBinderEnvironmentPostProcessor respects existing ineligible-definitions
* Add tests for KafkaStreamsBinderEnvironmentPostProcessor
> Improve KafkaStreams ineligible-definitions property handling

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/pom.xml
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryService.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryServiceMultiStateStoreTests.java
Fixes #2445
In KafkaStreams 3.0 the mechanism used to answer _“does this topology have this store?“_ was changed.
In 3.0 it asked the actual built topology which would not return a state store unless the KafkaStreams instance was actually using it:
```java
public <T> T store(StoreQueryParameters<T> storeQueryParameters) {
this.validateIsRunningOrRebalancing();
String storeName = storeQueryParameters.storeName();
if (this.taskTopology != null && this.taskTopology.hasStore(storeName) || this.globalTaskTopology != null && this.globalTaskTopology.hasStore(storeName)) {
return this.queryableStoreProvider.getStore(storeQueryParameters);
} else {
throw new UnknownStateStoreException("Cannot get state store " + storeName + " because no such store is registered in the topology.");
}
}
```
However …
> Make InteractiveQueryService only return used state stores

- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/BinderChildContextInitializer.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java
Previously, when running in AOT mode the binder child context was created w/ the same beans as when in JVM mode. The whole point of the former is to static initialize an empty fresh contextusing the AOT generated initializer.
@artembilan this addresses your concern in the initial commit of this feature.
> Use empty context for AOT binder child context

- binders/kafka-binder/pom.xml
Let the Kafka client versions be managed from Spring Boot rather than the binder manages it's own versions.
> Cleanup Kafka Client Deps

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryService.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsVersionAgnosticTopologyInfoFacade.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryServiceMultiStateStoreTests.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsInteractiveQueryIntegrationTests.java
This proposal solves the "does this streams app actually have this state store available?" question in a KafkaStreams version agnostic manner. 
The original complication (#2445) summarized:
> In KafkaStreams 3.1 the mechanism used to answer “does this topology have this store?“ was changed.
> 
> In 3.0 it asked the actual built topology which would not return a state store unless the KafkaStreams instance was actually using it.
> 
> However in 3.1+ it asks the topology metadata which will answer yes if any of its state factories have the state store, regardless if it used or not. This is a problem because SCSt adds all state stores beans to all KafkaStreams apps which in turns leads to IQS getting back unwanted/unused state stores from `getQueryableStore`.
The 1st [attempted …
> GH-2523:  Smarter state store resolution in InteractiveQueryService

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryService.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsVersionAgnosticTopologyInfoFacade.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsVersionAgnosticTopologyInfoFacadeTests.java
This PR ports the improvements made during the fix in the `3.2.x` branch. 
See the description on the [3.2.x PR](https://github.com/spring-cloud/spring-cloud-stream/pull/2533) as it is a good summary of this issue as a whole.
Closes #2523
> GH-2523: Port KafkaStreamsVersionAgnosticTopologyInfoFacade from 3.2.x

- docs/src/main/asciidoc/kafka/kafka_overview.adoc
noticed this when trying to implement
> Fix typo in ListenerContainerWithDlqAndRetryCustomizer example of kafka binder

- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java
When default binder is provided and multiple binder types are present on the classpath, then the binder requested as default is not instantiated when compiling in AOT mode.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2584
> Fixing AOT compilation with multi binders

- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/function/MultipleInputOutputFunctionTests.java
remove dead code in `MultipleInputOutputFunctionTests`.
`InputDestination` is instantiated and never used in the test code.
> Remove dead code in test

- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderTests.java
fix a message array index in kafka binder test code, so that the third message can be tested.
https://github.com/spring-cloud/spring-cloud-stream/blob/f1d4f8a53ef4110ae70b9bd2ce99cc26ef3feee1/binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderTests.java#L1761-L1768
> Fix a message array index in kafka binder test code

- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/integration/KafkaNullConverterTest.java
Enable a test that uses StreamBridge and KafkaNull together.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2614
Need this PR from Spring Cloud Function merged first: https://github.com/spring-cloud/spring-cloud-function/pull/981
> Enable KafkaNull converter tests

- docs/src/main/asciidoc/kafka/kafka_tips.adoc
Fix typos in kafka_tips.adoc
* serailzers -> serializers
* deserilzartion -> deserialization
* excepion -> exception
* excpetions -> exceptions
* errror -> error
* applicaiton -> application
* exaplain -> explain
* partiton, partititon -> partition
* biner -> binder
* reipce -> recipe
* becuase -> because
* configurarion -> configuration
* unncessary -> unnecessary
* sedings -> sendings
> Fix typos in kafka_tips.adoc

- docs/src/main/asciidoc/kafka/kafka_tips.adoc
* 1 fix on the default DLT name in `kafka_tips.adoc` according to the KafkaTopicProvisioner implementation.
* 2 minor fixes in `kafka_tips.adoc` code snippets
https://github.com/spring-cloud/spring-cloud-stream/blob/8e5f2d546ec3b0afa7d37a6903b7e4ab7d75b51d/binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/provisioning/KafkaTopicProvisioner.java#L320-L322
> fix the default DLT name in kafka_tips.adoc

- binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/utils/KafkaTopicUtils.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/EmbeddedHeaderUtils.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/converter/ObjectStringMessageConverter.java
- core/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/MessageConverterTests.java
Use StandardCharsets.UTF_8 instead of hardcoded "UTF-8".
It could make the codebase be cosistent with regards to using Charsets.
https://github.com/spring-cloud/spring-cloud-stream/blob/e1232ae7317d7a65bb92e0c6592a2858a3cc8ac9/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/converter/ObjectStringMessageConverter.java#L94
https://github.com/spring-cloud/spring-cloud-stream/blob/e1232ae7317d7a65bb92e0c6592a2858a3cc8ac9/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/converter/ObjectStringMessageConverter.java#L106
> Replace hardcoded "UTF-8" with StandardCharsets.UTF_8

- docs/src/main/asciidoc/README.adoc
Remove the gitter chat badge since the gitter channel is effectively closed.
https://gitter.im/spring-cloud/spring-cloud-stream?at=627a832ad4ef6e15af3c7c68
> Remove the gitter chat badge in the README

- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/binding/BindingServiceTests.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java
There are some use-cases when we need to know upfront if specific binding is really bound.
The goal is to prevent some security vulnerabilities when too many unexpected dynamic bindings, e.g.
via router based on the `StreamBridge`.
The `BindingService` provides for us `getProducerBindingNames()`
and `getConsumerBindingNames()` which are not optimal
for the task to check for binding presence
* Introduce `BindingService.getProducerBinding(String bindingName)` and `getConsumerBindings(String bindingName)` to cover a use-case when we need to check for predefined bindings.
This API might be useful in other use-case when we need to get access to managed bindings
Related to: https://github.com/spring-cloud/stream-applications/issues/330
> Add `BindingService.get*Binding(s)(String)` API

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/AbstractKafkaStreamsBinderProcessor.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/properties/KafkaStreamsConsumerProperties.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/EventTypeRoutingWithInferredSerdeTests.java
- docs/src/main/asciidoc/kafka/kafka-streams.adoc
In Kafka Streams binder, deserialization exception handler does not take effect when event type routing is enabled. Fixing this issue by allowing the applications to use the configured or inferred Serde rather than the byte[] Serde used by the event type router initially.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2613
> Event type routing and deserialization issues

- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderHealthIndicator.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderHealthIndicatorTest.java
When destination is pattern, even when the cluster is down, health indicator is erroneously reporting the status as UP. Addressing this issue by calling a simple listTopics on the consumer when the destination is pattern, and if it throws an exception, report the status as DOWN. If the call succeeds, we assume that the cluster is accessible.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2628
> Health indicator fixes when topic is pattern

- binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinder.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderConfiguration.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReceiverOptionsCustomizer.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/SenderOptionsCustomizer.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/test/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderIntegrationTests.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/test/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderTests.java
- docs/src/main/asciidoc/kafka/kafka-reactive.adoc
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2634
Allow customization of `ReceiverOptions` and `ProducerOptions`.
> GH-2634: Reactor Kafka Binder Customization

- core/spring-cloud-stream/pom.xml
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/BinderChildContextInitializer.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceConfiguration.java
- core/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/BinderChildContextInitializerTests.java
- core/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/DefaultBinderFactoryTests.java
- core/spring-cloud-stream/src/test/resources/binder-aot-test/application.yml
- Adds support for AOT child context generation for user-declared binder configurations.
- Add AOT processing test to verify single and multi-binder cases'
Fixes #2655
> GH-2655: AOT support user declared binders

- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java
- Sets the conversion service on AOT child binder contexts to allow complex properties to be bound in extended binding props
**NOTE** Update of AOT smoke tests in progress in other PR.
Fixes #2705
> GH-2705: AOT support complex binding properties

- binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinder.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/test/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderIntegrationTests.java
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2709
Add support for `...destinationIsPattern` as is supported by the message channel binder.
> GH-2709: Reactive Kafka Binder and Topic Patterns

- docs/src/main/asciidoc/index.adoc
- docs/src/main/asciidoc/spring-cloud-stream.adoc
- Fix issue where Kafka was called out as only binder that supported pause/resume
- Add dynamic publish option supported by solace
- Added Solace binder to main page
> Minor docs updates

- docs/src/main/asciidoc/kafka/kafka_tips.adoc
Current documentation had `kafka` missing from the configuration path.
> Correct configuration path for AckMode in the kafka tips document

- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/function/ImplicitFunctionBindingTests.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java
When using Reactive Kafka binder, it is allowed to have concurrency > 1. There is a check in FunctionConfiguration that throws an error if concurrency is > 1, when using reactive types. Since it is allowed to do so with Reative Kafka binder, switch this conversion into a warning log message.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2726
> Reactive Kafka Binder errors when concurrency > 1

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderUtils.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/function/FunctionDetectorCondition.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/function/KafkaStreamsFunctionBeanPostProcessor.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/bootstrap/KafkaStreamsBinderBootstrapTest.java
Kafka Streams functions declared in super classes are no longer detected by the binder discovery algorithms. Fixing this issue by properly scanning the methods from the super classes.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2737
> KafkaStreams Functions Detection Logic

- docs/src/main/asciidoc/binders.adoc
- docs/src/main/asciidoc/kafka/kafka-streams.adoc
- docs/src/main/asciidoc/kafka/kafka_overview.adoc
- docs/src/main/asciidoc/spring-cloud-stream.adoc
I found wrong formats on documentation.
1. `*{spring-cloud-stream-version}*`-> `*{project-version}*`
2. wrong formats of backtick
> Polish documentations

- core/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/BinderChildContextInitializerTests.java
The `BinderChildContextInitializerTests` is failing in Jenkins but not locally. 
This adds temporary sout to the test in order to see what the issue is in the child context creation.
> Instrument BinderChildContextInitializerTests to debug failure in CI

- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/MultipleOutputBindingsPartitionsTests.java
- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/function/MultipleInputOutputFunctionTests.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/PartitionAwareFunctionWrapper.java
- When using reactive functions, partition selector strategy does not use the configured partition count for multiple outbounds. This is because we take the first configured output binding and apply it's partition counts on all the outbound reactive streams (Tuples). Addressing this issue by properly applying the correct partition handling per output binding.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2750
> Multi output partition issues

- docs/src/main/asciidoc/kafka/kafka_overview.adoc
Tried to fix this issue https://github.com/spring-cloud/spring-cloud-stream/issues/2773
> Fix broken links in documentation

- docs/src/main/asciidoc/binders.adoc
- docs/src/main/asciidoc/sagan-index.adoc
- docs/src/main/asciidoc/spring-cloud-stream.adoc
Update Solace links to point directly to  binder docs in `solace-spring-cloud` project here: https://github.com/SolaceProducts/solace-spring-cloud/tree/master/solace-spring-cloud-starters/solace-spring-cloud-stream-starter#spring-cloud-stream-binder-for-solace-pubsub
Squash & merge suggested.
> Update outdated solace links

- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/integration/KafkaBindingServiceTests.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java
If a target middleware (Kafka for ex) topic has more partitions than what is set on the partition-count producer property, the binder never updates the original producer partition-count property to the partition count from the middleware if it is higher than what was given through the property. Because of this, te PartitionAwareFunctionWrapper which evaluates and assigns the partition header in Spring Cloud Stream does not compute the correct partition since the hash operation still using the original partition-count from the producer binding property. This commit is addressing this issue.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2796
> GH-2796: Fix partition count related issues

- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/pom.xml
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderHeaderMapper.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderUtils.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/PulsarMessageChannelBinder.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/config/PulsarBinderConfiguration.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/ConsumerConfigProperties.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/ProducerConfigProperties.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/PulsarBinderConfigurationProperties.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/PulsarConsumerProperties.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/PulsarExtendedBindingProperties.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/PulsarProducerProperties.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/ConsumerConfigPropertiesTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/ProducerConfigPropertiesTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderConfigurationPropertiesTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderIntegrationTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderUtilsTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarExtendedBindingPropertiesTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarTestContainerSupport.java
The PulsarBinder relies on the Spring Pulsar Spring Boot starter. The starter moved out of the spring-pulsar core repo and into Spring Boot proper. This commit updates the Pulsar binder to use the new coordinates for the Spring Boot based starter.
* Additionally, the PulsarProperties were greatly reduced in the move to Spring Boot. As such, the binder exposes an extended set of config properties for producer/consumer (the initial set supported before the property reduction).
> Update Pulsar binder to use new Spring Pulsar starter.

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/AbstractKafkaStreamsBinderProcessor.java
- When event-type routing is enabled in Kafka Streams binder and conurrency > 1 is used, messages are occasionally getting dispatched to the wrong consumer causing CCE. This is due to a race condition caused by a shared resource across threads. Fixing the issue by introducing a ThreadLocal variable.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2823
> GH-2823: Messages routed to the wrong consumer

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/DltAwareProcessor.java
Since exception is not propogated, adding a trace log allows an optional way for a developer to utilize the defaultRecoverer and still do some basic review of a given exception.
> Add DltAwareProcessor trace logging

- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java
- With pollable consumers, bindings actuator endpoint throws an exception since it cannot find the binding key in the bindings map (the key is stroed with the actual destination topic). Addressing this issue by quering the binding with the binding name.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2849
> GH-2849: Pollable consumers bindings endpoint

- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarExtendedBindingPropertiesTests.java
The default value for PulsarContainerProperties.subscriptionType was switched to `null` in https://github.com/spring-projects/spring-pulsar/commit/ed3899fcb9aee8e6767cdbe8275055a47fd22c47#diff-1371e1026362d375ef0f90846291add7cdcae0c340b934e3972d0bd72b312fa5L61.
This commit adjusts the PulsarExtendedBindingPropertiesTests 'extendedBindingsArePropagatedToContainerProperties' test for this fact.
> Fix failure in PulsarExtendedBindingPropertiesTests

- binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaBinderConfigurationProperties.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/test/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaBinderConfigurationPropertiesTest.java
When providing schema registry SSL properties under Kafka binder configuration, those properties are not being propagated to producer configurations and consumer configurations
This is necessary for certain serializer/deserializer to work. 
This change will fix https://github.com/spring-cloud/spring-cloud-stream/issues/2882 .
> Schema registry SSL config propagation to producer and consumer confgurations

- binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsMessageConversionDelegate.java
I've identified a thread safety issue in the `serializeOnOutbound` method of the `KafkaStreamsMessageConversionDelegate` class. Specifically, the usage of `PerRecordContentTypeHolder` is not thread-safe, which could lead to incorrect behavior in multi-threaded environments (For example when inbound topic has multiple partitions and and streams is processed conncurrently).
The issue arises in scenarios where the `serializeOnOutbound` method is invoked concurrently by multiple threads, leading to potential race conditions and incorrect handling of the `contentType` for each record.
I've implemented POC application for reproducing this scenario: https://github.com/LazroLeader/CloudStreamRaceConditionPOC
Each thread should have its own instance of `PerRecordContentTypeHolder` to ensure that …
> Thread Safety Issue in serializeOnOutbound Method of KafkaStreamsMessageConversionDelegate

- binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaBinderConfigurationProperties.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/test/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaBinderConfigurationPropertiesTest.java
* do not copy truststore, if "ssl.truststore.location" is set to empty string (e.g. ssl.truststore.location:{ENV_VARIABLE})
The Config worked until version 4.0.4 :-)
Error was:
`Caused by: java.lang.IllegalStateException: java.io.FileNotFoundException: class path resource [${TRUSTSTORE_PATH}] cannot be opened because it does not exist
at org.springframework.cloud.stream.binder.kafka.properties.KafkaBinderConfigurationProperties.moveCertsToFileSystemIfNecessary(KafkaBinderConfigurationProperties.java:199)
at org.springframework.cloud.stream.binder.kafka.properties.KafkaBinderConfigurationProperties.getKafkaConnectionString(KafkaBinderConfigurationProperties.java:183)
at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.normalalizeBootPropsWithBinder(KafkaTopic …
> Fixing empty truststore-config in Kafka Streams binder

- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderUtils.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/PulsarMessageChannelBinder.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/ConsumerConfigProperties.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/ProducerConfigProperties.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/ConsumerConfigPropertiesTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderIntegrationTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderUtilsTests.java
Running the Pulsar binder with Java 21 surfaced a bug where the layered binder/binding config props are not properly applied to the targeted consumer/producer builders.
The bug existed before Java 21 and is unrelated.
The binder/binding config props are converted to a Pulsar ProducerConfigurationData object via Jackson. This conversion process iterates over a map of config props. The iteration order of the map changed between Java 17 and 21. This results in object setters getting called in different orders which in turn causes cross field validation errors.
See #2915 for more details
> Fix Pulsar binder for Java 21

- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java
Load eagerly the `FunctionConfiguration`, even with `spring.main.lazy-initialization` property enabled, because the listeners must initialize at startup, otherwise, they won't work.
fixes #2919
> #2919 Load eagerly the configuration, even the lazy-init enabled

- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java
Sending kafka events from virtual thread causes pinning:
```
Thread[#83,ForkJoinPool-1-worker-6,5,CarrierThreads]
java.base/java.lang.VirtualThread$VThreadContinuation.onPinned(VirtualThread.java:183)
java.base/jdk.internal.vm.Continuation.onPinned0(Continuation.java:393)
java.base/java.lang.VirtualThread.parkNanos(VirtualThread.java:621)
java.base/java.lang.System$2.parkVirtualThread(System.java:2652)
java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:67)
java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:267)
java.base/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1866)
java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoi …
```
> Align sending kafka events from virtual threads

- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/function/StreamBridgeTests.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/MessageConverterConfigurer.java
- core/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binding/MessageConverterConfigurerTests.java
* When output-bindings config is explicitly used for StreamBridge and the RabbitMQ routing-key-expression is provided, Spring Cloud Stream is throwing an exception due to a proper function is not found in the catalog. Bypassing this step and let the bootstrapping continues if output-bindings and RabbitMQ routing-key-expression combo is used.
* Adding tests to verify
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2921
> GH-2921: Output-bindings and RabbitMQ r-k-e issues

- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/binder/tck/ContentTypeTckTests.java
- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/binding/BindingServiceTests.java
- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/BindingHandlerAdviseTests.java
- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/RetryTemplateTests.java
- core/spring-cloud-stream-test-binder/src/main/java/org/springframework/cloud/stream/binder/test/EnableTestBinder.java
- docs/modules/ROOT/pages/spring-cloud-stream.adoc
- docs/modules/ROOT/pages/spring-cloud-stream/spring_integration_test_binder.adoc
- Added the `@EnableTestBinder` annotation to import `TestChannelBinderConfiguration` for enabling TestBinder. This was decided in issue #2931.
- Replaced `@Import(TestChannelBinderConfiguration.class)` with `@EnableTestBinder` in the tests.
> Add @EnableTestBinder annotation

- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/BatchWithDlqCustomizerDisablesBinderDlqTests.java
Batch consumer with `ListenerContainerWithDlqAndRetryCustomizer` should disable binder-based DLQ.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2951
> GH-2951: Batch consumer and DLQ issues

- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java
Related to: https://github.com/spring-projects/spring-integration/issues/9362
After the fix in Spring Integration: https://github.com/spring-projects/spring-integration/commit/bdcb856a9081bc091d56be16d51f0f4d561bc9ce we ended up in a deadlock situation with a `beginPublishingTrigger` in the `FunctionConfiguration` used for the `delaySubscription()` on an original `Publisher`. The `FluxMessageChannel` uses its own `delaySubscription()` until the channel has its subscribers. Apparently the logic before was with errors, so the `FluxMessageChannel` was marked as active even if its subscriber is not ready yet, leading to famous `Dispatcher does not have subscribers` error. So, looks like this `beginPublishingTrigger` was introduced back in days in Spring Cloud Stream to mitigate that situation …
> Remove redundant `delaySubscription` from `FunctionConfiguration`

- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/function/HeaderTests.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java
Hello,
While working on a development related to Spring Cloud Stream, I noticed a situation that is also relevant to Spring Cloud Function.
To explain the issue clearly, we will first examine a method from Spring Cloud Function. The following method exhibits different behaviors. In some cases, it generates the output message using the input header, while in other cases, it does not consider the input header at all. This results in some variations in the code.
In other words, the code below can sometimes directly set the headers provided in the input to the output header. Sometimes, it creates the output headers without using the input headers.
Now, let's examine the method affected by the above code. I have written some tests, and based on the results, the target-protocol header is …
> Missing Headers Problem

- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/config/PulsarBinderConfiguration.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/provisioning/PulsarTopicProvisioner.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderTests.java
- binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarTopicProvisionerTests.java
- bom/spring-cloud-starter-parent/pom.xml
Spring for Apache Pulsar introduced support for default tenant and namespace for Pulsar topics in https://github.com/spring-projects/spring-pulsar/commit/6d23378fbb57a50c3a302be136f9173d2854085d. 
This ensures that all topic names are fully-qualified (using the default tenant and namespace when not fully-qualified).
> Use PulsarTopicBuilder in Pulsar binder

- core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/binder/ErrorBindingTests.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java
When using multiple destinations for one binding, the errors are logged as many times as the number of destinations.
For an example, when an error occurs in the following binding : 
```
spring.cloud.stream.bindings.process-in-0.consumer.max-attempts=1
spring.cloud.stream.bindings.process-in-0.destination=one,two,three
```
This results in three successive logs from the `org.springframework.integration.handler.LoggingHandler`
This pull request fixes this by bridging only once the bindingErrorHandler whith the globalErrorHandler
> Avoid duplicate error logging when multiple destinations per binding

- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java
This PR simplifies the logic for assigning outputBindings in the FunctionConfiguration file by eliminating redundant checks and method calls. The original implementation checked bindingProperties.getOutputBindings() twice, which was unnecessary and could lead to confusion. The updated version performs the check once, reducing the code complexity and improving readability.
> Simplify outputBindings assignment logic in FunctionConfiguration

- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java
Resolves #3004
This pull request includes changes to the `DefaultBinderFactory` class to improve thread safety by introducing a `ReentrantLock`. The most important changes include adding the lock, modifying the `getBinder` method to use the lock, and ensuring the lock is released properly.
Thread safety improvements:
* [`core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java`](diffhunk://#diff-171a19cc53e372c53aa61e31f2cbacd26851f2cdef5e848529f65a92e685c381R33): Imported `ReentrantLock` and declared a static final instance of it. [[1]](diffhunk://#diff-171a19cc53e372c53aa61e31f2cbacd26851f2cdef5e848529f65a92e685c381R33) [[2]](diffhunk://#diff-171a19cc53e372c53aa61e31f2cbacd26851f2cdef5e848529f65a92e685c381R102-R103)
* …
> Change the use of synchronized in the getBinder method of DefaultBinderFactory class for virtual-threads compliant

- docs/modules/ROOT/pages/rabbit/rabbit_overview/binder-properties.adoc
Currently docs display the correct prefix as spring.cloud.stream.binder where it should be spring.cloud.stream.rabbit.binder
> Update docs to show correct prefix for connection-name-prefix

- docs/modules/ROOT/pages/kafka/kafka-binder/config-options.adoc
I'm pretty sure it's 60:
https://github.com/spring-cloud/spring-cloud-stream/blob/main/binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaBinderConfigurationProperties.java#L122 (and in my tests too).
> Docs: Update timeout default

- docs/modules/ROOT/pages/spring-cloud-stream/overview-error-handling.adoc
Fixes a typo in the Spring Cloud Stream documentation.
> Fix typo in overview-error-handling.adoc

- docs/modules/ROOT/pages/spring-cloud-stream/overview-error-handling.adoc
Also fixed that the `note` section was not rendered as a note because of missing new line.
> Clarify that having a custom error handler disables auto send to DLQ

- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderMetrics.java
- binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderMetricsTest.java
- core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java
Fixes: https://github.com/spring-cloud/spring-cloud-stream/issues/3062
The `KafkaBinderMetrics` creates `KafkaConsumer` instances and schedule the fix rate task for them, but never closes them even when the `scheduler` is shut downed
* Implement a `Lifecycle` contract in the `KafkaBinderMetrics` and call `close()` from the `stop()` to satisfy CRaC resource management expectations.
* Also close all the `KafkaConsumer` instances from the `metadataConsumers`
**Cherry-pick to `4.1.x`**
> GH-3062: Fix `KafkaBinderMetrics` for resource leaks

- binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/provisioning/KafkaTopicProvisioner.java
fix(kafka-topic-provisioner): Prevent resource leak on binding producer to KafkaMessageChannelBinder
- Producer that fetches partition info now initializes within a try-with-resources block
- If exceptions occur on calling producer.partitionsFor(topicName), it's now properly closed and resources are released
> fix(kafka-topic-provisioner): Prevent resource leak

- docs/modules/ROOT/pages/kafka/kafka-streams-binder/record-serialization-and-deserialization.adoc
Should be `useNativeEncoding`, not `nativeEncoding`: https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_kafka_streams_producer_properties
> Fix typo in record-serialization-and-deserialization doc
