spring-cloud-stream-module-launcher/Dockerfile

No longer need the add the contents of artifacts to the docker image.

Removed add for the artifacts/modules

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/DirectChannelFactoryBean.java

DirectChannelFactoryBean should set the bean name and bean factory on created instance.

DirectChannelFactoryBean should set the bean name and bean factory

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/annotation/Input.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/annotation/Output.java

So that they can qualify @Bean method arguments

Allow method parameters as target for @Input and @Output

---

spring-cloud-stream-module-launcher/src/main/java/org/springframework/boot/loader/ModuleJarLauncher.java
spring-cloud-stream-module-launcher/src/main/java/org/springframework/cloud/stream/module/launcher/ModuleLauncher.java
spring-cloud-stream-module-launcher/src/main/java/org/springframework/cloud/stream/module/utils/ClassloaderUtils.java

Aligns the classloader creation strategy of the aggregated module with regular modules.
- application classpath URLs are added to the launched aggregated module as well

Aligns the classloader creation strategy of the aggregated module with regular modules

---

spring-cloud-stream-module-launcher/src/main/java/org/springframework/cloud/stream/module/launcher/ModuleJarLauncher.java
spring-cloud-stream-module-launcher/src/main/java/org/springframework/cloud/stream/module/launcher/ModuleLauncher.java

This change requires https://github.com/spring-projects/spring-boot/pull/3741

Use JarLauncher for module launcher

---

pom.xml

GH-224: Update to SI 4.2.3.RELEASE

---

spring-cloud-stream-binders/pom.xml
spring-cloud-stream-binders/spring-cloud-stream-binder-kafka/pom.xml
spring-cloud-stream-binders/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaTestBinder.java
spring-cloud-stream-binders/spring-cloud-stream-binder-redis/pom.xml
spring-cloud-stream-binders/spring-cloud-stream-binder-redis/src/test/java/org/springframework/cloud/stream/binder/redis/AbstractRedisSerializerTests.java
spring-cloud-stream-binders/spring-cloud-stream-binder-test/pom.xml
spring-cloud-stream-binders/spring-cloud-stream-binder-test/src/test/java/org/springframework/cloud/stream/binder/MessageChannelBinderSupportTests.java
spring-cloud-stream-starters/pom.xml

- Use spring-cloud-stream-tuple instead
This resolves #280

Remove Spring XD tuple dependency

---

spring-cloud-stream-test-support-internal/src/main/java/org/springframework/cloud/stream/test/junit/kafka/KafkaTestSupport.java

-minor change in KafkaTestSupport to add a getter for KafkaServer.

Kafka Test Support

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/MessageHistoryTrackerConfigurer.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingProperties.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/ChannelBindingServiceProperties.java

Fix boolean getter methods

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/Binder.java

- `module` to `app`
- Add more detail to the javadoc

Binder interface javadoc

---

mvnw

Update mvnw to determine profile on mac and linux

---

spring-cloud-stream-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc

Update headerMode property in doc

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/aggregate/AggregateApplication.java
spring-cloud-stream/src/test/java/org/springframework/cloud/stream/aggregation/ModuleAggregationTest.java

Fixes #474
- Now the only API for aggregating is AggregateApplicationBuilder
- add namespace tests

Make AggregateApplication package local

---

spring-cloud-stream-dependencies/pom.xml

Upgrade RxJava to 1.1.5

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/aggregate/AggregateApplication.java

- Make sure to set the appropriate mainApplicationClass name for the child applications
This resolves #562

Fix mainApplicationClass for child contexts

---

spring-cloud-stream-dependencies/pom.xml
spring-cloud-stream-docs/pom.xml

Resolves spring-cloud/spring-cloud-stream#580

gh-580 Include API Docs in Docs Zip

---

spring-cloud-stream-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc

change STANDARD_REQUEST_HEADERS to STANDARD_REPLY_HEADERS where appropriate

Fix copy-paste-o

---

pom.xml
spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/ReactiveSupportAutoConfiguration.java
spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/reactor/core/scheduler/ElasticScheduler.java
spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/reactor/core/scheduler/NoInterruptOnCancelSchedulerFactory.java
spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/reactor/core/scheduler/ParallelScheduler.java
spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/reactor/core/scheduler/SingleScheduler.java
spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/reactor/core/scheduler/SingleTimedScheduler.java
spring-cloud-stream-reactive/src/test/java/org/springframework/cloud/stream/reactive/StreamListenerInterruptionTests.java
spring-cloud-stream-tools/src/main/resources/checkstyle-suppressions.xml

Workaround for https://github.com/reactor/reactor-core/issues/159

Override scheduler implementations for Reactor 3.0.0

---

spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/MessageChannelToInputFluxParameterAdapter.java
spring-cloud-stream-reactive/src/test/java/org/springframework/cloud/stream/reactive/MessageChannelToInputFluxParameterAdapterTests.java

Subscribers to channel-wrapping `Flux` instances should broadcast

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/aggregate/AggregateApplicationBuilder.java

Reinstate no-arg constructor for AggregateApplicationBuilder

---

spring-cloud-stream/pom.xml

Adds 'spring-boot-starter-validation' as a mandatory dep

---

spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc

Add doc for aggregate application namespace prefix

---

spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/ObservableToMessageChannelResultAdapter.java

Fix compilation issue on ObservableToMessageChannelResultAdapter

---

spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/InboundJsonToTupleConversionTest.java
spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/MessageChannelConfigurerTests.java
spring-cloud-stream-integration-tests/src/test/resources/org/springframework/cloud/stream/config/inboundjsontuple/inbound-json-tuple.properties
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/converter/TupleJsonMessageConverter.java

Restore support for application/json in TupleJsonMessageConverter

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceConfiguration.java

- Remove `ConditionalOnMissingBean` on StreamListenerAnnotationBeanPostProcessor

Fix BindingServiceConfiguration

---

spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
spring-cloud-stream-schema-server/src/test/java/org/springframework/cloud/stream/schema/server/SchemaRegistryServerAvroTests.java

Doc for schema server REST endpoint /schema/format

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java

Allow non byte array payload with raw HeaderMode

---

spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc

Fix metrics properties prefix

---

spring-cloud-stream-metrics/src/main/java/org/springframework/cloud/stream/metrics/ApplicationMetricsProperties.java

Clear the `exportProperties` cache on refresh

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceConfiguration.java
spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/SourceBindingWithBindingTargetsTests.java

Fix #962
Postpone resolution of GH-943 until the resolution
of https://jira.spring.io/browse/INT-4276

Revert contentType propagationChanges

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/annotation/StreamListener.java

Fixing StreamListener javadoc issues

---

pom.xml
spring-cloud-stream-binder-test/pom.xml
spring-cloud-stream-codec/pom.xml
spring-cloud-stream-core-docs/pom.xml
spring-cloud-stream-integration-tests/pom.xml
spring-cloud-stream-metrics/pom.xml
spring-cloud-stream-reactive/pom.xml
spring-cloud-stream-rxjava/pom.xml
spring-cloud-stream-schema-server/pom.xml
spring-cloud-stream-schema/pom.xml
spring-cloud-stream-test-support-internal/pom.xml
spring-cloud-stream-test-support/pom.xml
spring-cloud-stream-tools/pom.xml
spring-cloud-stream/pom.xml

Updating to next major release line: 1.3.0.BUILD-SNAPSHOT

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/EnvironmentEntryInitializingTreeMap.java

Binder.get was missing conversion service configuration and failing on parse of properties

Passing Conversion service to boot Binder

---

spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/AbstractAvroMessageConverter.java

Fixes issue with originalContentType

---

.travis.yml
pom.xml

Add codecov support

---

pom.xml

Remove redundant groupId declaration in the parent scst pom.xml

---

spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/StreamListenerMethodRegisteredOnlyOnceTest.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerAnnotationBeanPostProcessor.java

StreamListener methods are registered twice with proxies

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java

Disabled logStartupInfo on child context

---

spring-cloud-stream-binder-test/src/main/java/org/springframework/cloud/stream/binder/AbstractTestBinder.java

Added assertion to org.springframework.cloud.stream.binder.AbstractTestBinder to ensure that MessageChannels that are passed to any of the bind methods are configured with Message Interceptors

Added MessageChannel configuration assertion

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/MessageSerializationUtils.java

Fixed contentType equals logic to compare only  and

GH-1121 Fixed contentType equals logic

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java

Fixes: spring-cloud/spring-cloud-stream#1159
* Extract `EmbeddedHeadersChannelInterceptor` class for better navigation
* Use only one shared instance of this interceptor since it is stateless
* Add this `EmbeddedHeadersChannelInterceptor` in the position `0` to
extract embedded headers first
The fix confirmed by Kafka and Kinesis binders

GH-1159 Extract EmbeddedHeaders first on consumer

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceConfiguration.java

Fixes: spring-cloud/spring-cloud-stream#1170
The `messageHandlerHeaderPropagationBeanPostProcessor` causes early
`BeanFactory` initialization via its `SpringIntegrationProperties`
dependency.
This triggers an initialization all the `@ConfigurationProperties`
infrastructure in Spring Boot, when we might not have all the necessary
beans, e.g. `Converter` for some configuration property
* Eliminate the "early `BeanFactory` initialization syndrome" through
the `SmartInitializingSingleton`
**Cherry-pick to 1.3.x**

GH-1170: Fix early BeanFactory initialization

---

index.html

Add info about Kafka 0.11 with 1.3.x

---

spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binding/BindingServiceTests.java

Fixes https://github.com/spring-cloud/spring-cloud-stream/issues/1193

GH-1193: Fix test race condition

---

spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/1205

GH-1205: Partitioning Doc Polishing

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/Binding.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinding.java

Added support for displaying
- state
- pausable
- name/group
- destination info
- extended binding info
- etc
Resolves #1054

GH-1054 Added support for display extra binding information

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/ConsumerProperties.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingServiceProperties.java

updated javadocs in BindingServiceProperties
Resolves #1249

GH-1249 added javadocs to ConsumerProperties

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/micrometer/ApplicationMetrics.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/micrometer/ApplicationMetricsProperties.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/micrometer/DefaultDestinationPublishingMeterRegistry.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/micrometer/DestinationPublishingMetricsAutoConfiguration.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/micrometer/Metric.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/micrometer/MetricsPublisherConfig.java

- brought back the Metric class from the old boot
- modified Metric class slightly to adjust for the type of info available thru micrometer
- added 'meterFilter' property for metric filtering
Resolves #1324

GH-1324 Restored support for the old format of metric Message

---

spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc

GH-1257 Updated Metrics documentation

---

spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc

GH-1333 created Error Handling section

---

spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/annotation/StreamRetryTemplate.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractBinder.java

Added @StreamRetryTemplate qualifier annotation
Resolves #1405

GH-1405 added RetryTemplate qualifier

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java

Remove ConditionalOnProperty

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/EmbeddedHeaderUtils.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/AbstractBindingLifecycle.java

Code inspection was displayed in IntelliJ and it was fixed.

Simplify code

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionInvoker.java
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamFunctionProperties.java
spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/FunctionInvokerTests.java
spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/FuntionPropertiesTest.java
spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/pojo/Baz.java
spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/pojo/ErrorBaz.java
spring-cloud-stream/src/test/resources/org/springframework/cloud/stream/binder/cloud-function-test.properties

Fixed native encoding for output of invoked function.

---

2.1.0.RC1/spring-cloud-stream.xml
font-awesome/font/fontawesome-webfont.svg
spring-cloud-stream.xml

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were fixed, but the https status was not OK. However, the https status was the same as the http request or http redirected to an https URL, so they were migrated. Your review is recommended.
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/ ([https](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/) result 404).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/ …

URL Cleanup

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BinderFactoryConfiguration.java

The `HandlerMethodArgumentResolversHolder` has been deprecated in SI-5.1
and now it is removed in SI-5.2
To make current Spring cloud Stream compatible with the latest Spring Boot,
which is pulled by the latest Spring Cloud, remove usage of that
deprecated class in the current version in favor of internal logic
applied in the SI
Looks like the `BinderFactoryConfiguration` is deprecated as well and
is going to be removed in the future release anyway

Remove usage of deprecated code

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java
spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/PollableConsumerTests.java

Fix pollable consumer auto-startup

---

docs/src/main/asciidoc/preface.adoc
docs/src/main/asciidoc/spring-cloud-stream.adoc
pom.xml
spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java
spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/ImplicitFunctionBindingTests.java

Add Spring Integration as function docs

Add Spring Integration as function sample

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/DefaultPollerProperties.java

cron and initialDelay properties in DefaultPollerProperties
Resolves #1903

Add missing properties in DefaultPollerProperties

---

docs/src/main/asciidoc/spring-cloud-stream.adoc

Removed context.getBean(InputDestination.class); line.

Documentation: correction in examples

---

docs/src/main/asciidoc/spring-cloud-stream.adoc

Minor typo

---

docs/src/main/asciidoc/binders.adoc
docs/src/main/asciidoc/ghpages.sh
docs/src/main/asciidoc/spring-cloud-stream.adoc

Wording changes

---

spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinding.java

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2135

Make DefaultBinding lifecycle methods non-final

---

docs/src/main/asciidoc/spring-cloud-stream.adoc

Content Type Negotiation

---

spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/StreamBridgeTests.java

This pull request contains a test that reproduces issue 2266
In the parameters, if you specify "--spring.cloud.stream.dynamic-destination-cache-size=2" instead of 1 the test passes. 
The test should pass whatever the value of "dynamic-destination-cache-size"

GH-2266 Add test to ensure GlobalChannelInterceptor is not added multiple times to the MessageChannels

---

docs/src/main/asciidoc/spring-cloud-stream.adoc

Improved language in the Bindings chapter.

Language improvement spring-cloud-stream docs

---

core/docs/src/main/asciidoc/preface.adoc
core/docs/src/main/asciidoc/spring-cloud-stream.adoc

GH 2290 Fix wrong image URL

---

binders/rabbit-binder/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitMessageChannelBinder.java

Add connectionFactory getter

---

binders/kafka-binder/docs/src/main/asciidoc/overview.adoc

Based on suggestions in https://github.com/spring-cloud/spring-cloud-stream/issues/2313. Hope the edit helps.

Update documentation for ListenerContainerWithDlqAndRetryCustomizer

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinder.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/test/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderTests.java

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2297

GH-2297: Concurrency in Reactor Kafka Binder

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderEnvironmentPostProcessor.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderEnvironmentPostProcessorTests.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/SerdeResolverUtilsTests.java

* Fixes a failure in testcase in SerdeResolverUtilsTests
* Cherry picks 2 commits that improve the SerdeResolverUtilsTests and ineligible-definitions property handling

Fix and improve SerdeResolverUtilsTests 

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/pom.xml
binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryService.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryServiceMultiStateStoreTests.java

Backport of https://github.com/spring-cloud/spring-cloud-stream/commit/0cb59496fef59226afafbda464230231b38b0386

Make InteractiveQueryService only return used state stores (backport)

---

binders/kafka-binder/pom.xml
pom.xml

@trevormarshall 
@sobychacko 
@spencergibb 
Let's see what this does.

Adjust maven surefire plugin to avoid OOME in Jenkins

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/provisioning/KafkaTopicProvisioner.java

Don't Create an AdminClient if autoCreateTopics is False
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2486

AdminClient usage if autoCreateTopics is disabled

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryService.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryServiceMultiStateStoreTests.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsInteractiveQueryIntegrationTests.java

This proposal modifies the mechanism used to resolve (choose) state store in `InteractiveQueryService#getQueryableStore`. 
The current mechanism relies on the `KafkaStreams.StreamsMetadataState` which is not reliable unless the `application.server` streams config property is set. For a KafkaStreams app w/ a single instance this should not have to be set. 
The new mechanism does a couple of things:
1. only goes into the "resolve the store" logic when in fact there are multiple state store candidates
2. does not use the above mechanism (StreamsMetadataState) but rather the `topologyMetadata.sourceTopics`
The 1st commit does not change anything other than modify the existing tests so that they surface the bug. They previously were not verifying this.
Actual code change described above.
Fixes …

Smarter state store resolution for InteractiveQueryService

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsVersionAgnosticTopologyInfoFacade.java

Changes were made to the `KafkaStreamsVersionAgnosticTopologyInfoFacade` in the main branch. This PR just syncs those changes here as they are improvements to the previous commit.

GH-2523: Update topology facade to match impl in main branch

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/pom.xml

fix: set "spring-kafka-test" scope to "test"

---

docs/src/main/asciidoc/rabbit/rabbit_overview.adoc

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2554

Fix Doc ToC (3.2.x)

---

core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/function/StreamBridgeTests.java
core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java
core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamOperations.java
docs/src/main/asciidoc/spring-cloud-stream.adoc

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2548

StreamOperations interface for StreamBridge

---

docs/src/main/asciidoc/kafka/kafka_partitions.adoc

Extend docs on default partitioning strategy in Kafka binder

---

docs/src/main/asciidoc/spring-cloud-stream.adoc

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2598

Fix test binder docs

---

binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java
binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderTests.java
docs/src/main/asciidoc/kafka/kafka_overview.adoc

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2317

Supporting DLQ in batch mode

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryService.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBindingInformationCatalogue.java
docs/src/main/asciidoc/kafka/kafka_overview.adoc
samples/kafka-binder-native-app/README.adoc
samples/stream-function-batch-producer-consumer/README.adoc
samples/stream-function-batch-producer-consumer/mvnw
samples/stream-function-batch-producer-consumer/mvnw.cmd
samples/stream-function-batch-producer-consumer/pom.xml
samples/stream-function-batch-producer-consumer/src/main/java/sample/stream/batch/CloudStreamsFunctionBatch.java
samples/stream-function-batch-producer-consumer/src/main/java/sample/stream/batch/KafkaStreamFunctionBatch.java
samples/stream-function-batch-producer-consumer/src/main/resources/application.yml

Adding a clearer example as suggested by @sobychacko in https://github.com/spring-cloud/spring-cloud-stream-samples/pull/240.
This addition provides a concrete working example of using Batch Consumers and Batch Producers as documented [here](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_batch_consumers)
Let me know if anything isn't up to Spring Cloud standards or any updates need to be made!

Stream batch produce consume

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinder.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReceiverOptionsCustomizer.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/SenderOptionsCustomizer.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/test/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderIntegrationTests.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/test/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderTests.java

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2685
Required to allow customization of serializers/deserializers.

GH-2685: Reactive Kafka Customizers - Add Generics

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinder.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/test/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderTests.java
docs/src/main/asciidoc/kafka/kafka-reactive.adoc

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2691

GH-2691: Kafka Reactive Binder Support Multiplex

---

docs/src/main/asciidoc/spring-cloud-stream.adoc

- Docs on mixing test binder and the actual middleware based binder.
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2684

Enhancing docs on the usage of test binder

---

docs/src/main/asciidoc/spring-cloud-stream.adoc

Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2699

Clarify docs for binding keys with special chars

---

core/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/DefaultBinderTests.java

I am currently opening a PR for improving code for default binder as I found when doing pitman testing some of the scenarios were light for a few of the packages.  This for an open source project for my course as well to begin to try and contribute back to software that I utilize as well.

add test for improving coverage defaultbinder

---

binders/pom.xml
binders/pulsar-binder/pom.xml
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/pom.xml
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderHeaderMapper.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderUtils.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/PulsarMessageChannelBinder.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/config/PulsarBinderConfiguration.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/package-info.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/PulsarBinderConfigurationProperties.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/PulsarBindingProperties.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/PulsarConsumerProperties.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/PulsarExtendedBindingProperties.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/PulsarProducerProperties.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/properties/package-info.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/provisioning/PulsarTopicProvisioner.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/java/org/springframework/cloud/stream/binder/pulsar/provisioning/package-info.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/main/resources/META-INF/spring.binders
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/AbstractPulsarTestBinder.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderConfigurationPropertiesTests.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderHeaderMapperTests.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderIntegrationTests.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderTests.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderUtilsTests.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarExtendedBindingPropertiesTests.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarTestBinder.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarTestContainerSupport.java
binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarTopicProvisionerTests.java

- Moving Pulsar binder from the old 4.1.x branch

Initial migration of Pulsar binder

---

binders/kafka-binder/spring-cloud-stream-binder-kafka-core/pom.xml
binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/common/AbstractKafkaBinderHealthIndicator.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/common/TopicInformation.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinder.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderHealthIndicator.java
binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/test/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinderHealthIndicatorTests.java
binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderHealthIndicator.java
binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderMetrics.java
binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java
binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderHealthIndicatorTest.java
binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderMetricsTest.java
binders/kafka-binder/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderTests.java

- Provide a new abstraction for general Kafka binder related HealthIndicators.
- Refactor Kafka binder to use the new abstraction
- Add HealthIndicator implementation for the ReactorKafkaBinder
Resolves https://github.com/spring-cloud/spring-cloud-stream/issues/2752

Reactor Kafka Binder Health Indicator

---

docs/src/main/asciidoc/spring-cloud-stream.adoc

Hi, i found it when read document.
I think it would be good to add a word space. 😄

add word spacing

---

docs/src/main/asciidoc/schema-registry/spring-cloud-stream-schema-registry.adoc

I found some outdated information in the Schema Registry Server documentation, which made it difficult to try out. I will try to correct it.

Schema registry doc corrections

---

docs/src/main/asciidoc/spring-cloud-stream.adoc

After https://github.com/spring-cloud/spring-cloud-stream/issues/2626 some documtations ware not updated according to changes

Fix documentation related to explicit binding name change

---

docs/src/main/asciidoc/kafka/kafka_overview.adoc

At the company where I work we had to implement a similar solution to set up monitoring alerts and help better identify where the root cause of the problem is, I think this example can help other teams as well.

Added example to identify if kafka error is in brokers or in topic

---

core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BinderProperties.java

Fix typo in BinderProperties

---

docs/src/main/asciidoc/kafka/kafka_overview.adoc

fixes typo in setting DLQ

---

binders/pulsar-binder/spring-cloud-stream-binder-pulsar/src/test/java/org/springframework/cloud/stream/binder/pulsar/PulsarBinderIntegrationTests.java

Spring Pulsar 1.1.x introduced a new method `getPulsarClient` on `PulsarProducerFactory` 
and the `PulsarBinderIntegrationTests` has a custom factory that must be updated in order 
to run on both Pulsar 1.0.x and 1.1.x (i.e. Spring Boot 3.2.x and 3.3.x).

Fix custom test PulsarProducerFactory

---

core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinding.java
docs/modules/ROOT/pages/spring-cloud-stream/producing-and-consuming-messages.adoc

- Remove deleted `@EnableBinding`
- Replace example of `IntegrationFlow` documentation
- https://github.com/spring-projects/spring-integration/blob/95c7c8623c6bfef73f8a12e3ffad47c61649ea8b/spring-integration-core/src/main/java/org/springframework/integration/dsl/BaseIntegrationFlowDefinition.java#L2650-L2672

Remove and replace not available codes

---

core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/binder/ErrorBindingTests.java
core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java

Avoid duplicate error logging when multiple destinations per binding
